{
    TitleDef = {
        [1] = {
            HideType = 0,
            JumpID = 0,
            Group = 1,
            IsActive = 0,
            Obtain = [[集齐收集系统中的探险小队主题，即可获得]],
            ItemID = 95001,
            TitleId = 1,
            Describe = [[唤醒带着羽毛、武器的丛林冒险回忆的独特称号]],
            BeginTime = 0,
            Clt_version = [[1.18.0]],
            Name = [[探险小队]],
        } ,
        [2] = {
            HideType = 0,
            JumpID = 0,
            Group = 1,
            IsActive = 0,
            Obtain = [[集齐收集系统中的缤纷彩虹主题，即可获得]],
            ItemID = 95002,
            TitleId = 2,
            Describe = [[气球、彩虹、云朵装点起来的甜美称号]],
            BeginTime = 0,
            Clt_version = [[1.18.0]],
            Name = [[缤纷彩虹]],
        } ,
        [3] = {
            HideType = 0,
            JumpID = 0,
            Group = 1,
            IsActive = 0,
            Obtain = [[集齐收集系统中的探险小队主题，即可获得]],
            ItemID = 96001,
            TitleId = 1,
            Describe = [[唤醒带着羽毛、武器的丛林冒险回忆的独特称号]],
            BeginTime = 0,
            Clt_version = [[1.18.0]],
            Name = [[探险小队（3天）]],
        } ,
        [4] = {
            HideType = 0,
            JumpID = 0,
            Group = 1,
            IsActive = 0,
            Obtain = [[集齐收集系统中的缤纷彩虹主题，即可获得]],
            ItemID = 96002,
            TitleId = 2,
            Describe = [[气球、彩虹、云朵装点起来的甜美称号]],
            BeginTime = 0,
            Clt_version = [[1.18.0]],
            Name = [[缤纷彩虹（3天）]],
        } ,
    } ,
} 